//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/*
 * https://www.codeproject.com/Tips/646359/M-NET
 */

package m1.Properties;

//@global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()
//@global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")
class Settings {

    private static final Settings defaultInstance = new Settings();

    public static Settings getDefault() {
        return defaultInstance;
    }
}
